import turtle

turtle.up()
turtle.goto(0, 35)
turtle.down()
turtle.color('red')
turtle.fillcolor('blue')
turtle.circle(40)
turtle.up()
turtle.goto(0, -20)
turtle.down()
turtle.color('yellow')
turtle.fillcolor('yellow')
turtle.circle(40)
turtle.up()
turtle.goto(0, -75)
turtle.down()
turtle.color('green')
turtle.fillcolor('green')
turtle.circle(40)
